version: '3.1'

services:

  mongo2:
    image: mongo
    restart: always
    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: fitness
    ports:
      - 27017:27017
    volumes:
      - .:/data/db2

  myapplication:
    image: myapp:1.0
    environment:
      DB_HOST: mongo2
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: fitness
      DB_PORT: 27017
    ports:
      - 8000:8000
    depends_on:
      - mongo2
    build: .
    stdin_open: true
    tty: true
